import {
  ATTACK_DIE_FACES,
  DAMAGE_DIE_FACES,
  DEFENSE_DIE_FACES,
  ENEMY_DIE_FACES,
  EXTRA_SELECT_DIE_FACES,
  HYBRID_DIE_FACES,
  MULTIPLY_ATTACK_DIE_FACES,
  MULTIPLY_DEFENSE_DIE_FACES,
} from "./diceBlueprints";

import type { ItemBlueprint } from "../types/inventoryTypes";

/**
 * A registry containing all available item blueprints in the game.
 *
 * Each blueprint defines the static, non-changing data of an item such as:
 * - visual appearance
 * - footprint size
 * - base stats
 * - per-level stat progression
 * - rarity, category, base value
 *
 * Blueprints serve as templates from which runtime instances are created.
 *
 * @remarks
 * The key of the record is the blueprint's unique ID.
 */
const ItemBlueprints: Record<string, ItemBlueprint> = {
  green1: {
    id: "green1",
    name: "green1",
    space: [
      [0, 1],
      [0, 1],
      [1, 1],
      [0, 1],
    ],
    image: "items/green1.png",
    baseValue: 2,
    rarity: 2,
    categories: ["green"],
    dice: ATTACK_DIE_FACES,
  },
  green2: {
    id: "green2",
    name: "green2",
    space: [
      [0, 1, 0],
      [1, 1, 1],
    ],
    image: "items/green2.png",
    baseValue: 5,
    rarity: 1,
    categories: ["green"],
    dice: ATTACK_DIE_FACES,
  },
  green3: {
    id: "green3",
    name: "green3",
    space: [
      [0, 1, 1],
      [0, 1, 0],
      [0, 1, 0],
      [1, 1, 0],
    ],
    image: "items/green3.png",
    baseValue: 1,
    rarity: 2,
    categories: ["green"],
    dice: ATTACK_DIE_FACES,
  },
  green4: {
    id: "green4",
    name: "green4",
    space: [
      [1, 0],
      [1, 1],
    ],
    image: "items/green4.png",
    baseValue: 8,
    rarity: 1,
    categories: ["green"],
    dice: DEFENSE_DIE_FACES,
  },
  green5: {
    id: "green5",
    name: "green5",
    space: [
      [0, 1, 0],
      [0, 1, 1],
      [1, 1, 0],
    ],
    image: "items/green5.png",
    baseValue: 2,
    rarity: 0,
    categories: ["green"],
    dice: DEFENSE_DIE_FACES,
  },
  green6: {
    id: "green6",
    name: "green6",
    space: [
      [1, 0],
      [1, 1],
      [0, 1],
    ],
    image: "items/green6.png",
    baseValue: 5,
    rarity: 1,
    categories: ["green"],
    dice: DEFENSE_DIE_FACES,
  },
  violet1: {
    id: "violet1",
    name: "violet1",
    space: [
      [1, 1],
      [1, 1],
    ],
    image: "items/violet1.png",
    baseValue: 5,
    rarity: 4,
    categories: ["violet"],
    dice: HYBRID_DIE_FACES,
  },
  violet2: {
    id: "violet2",
    name: "violet2",
    space: [
      [0, 1, 0],
      [1, 1, 0],
      [0, 1, 1],
    ],
    image: "items/violet2.png",
    baseValue: 2,
    rarity: 2,
    categories: ["violet"],
    dice: HYBRID_DIE_FACES,
  },
  violet3: {
    id: "violet3",
    name: "violet3",
    space: [
      [1, 1],
      [1, 1],
      [0, 1],
      [0, 1],
    ],
    image: "items/violet3.png",
    baseValue: 1,
    rarity: 2,
    categories: ["violet"],
    dice: HYBRID_DIE_FACES,
  },
  violet4: {
    id: "violet4",
    name: "violet4",
    space: [
      [1, 0],
      [1, 0],
      [1, 1],
    ],
    image: "items/violet4.png",
    baseValue: 5,
    rarity: 2,
    categories: ["violet"],
    dice: ENEMY_DIE_FACES,
  },
  violet5: {
    id: "violet5",
    name: "violet5",
    space: [[1], [1]],
    image: "items/violet5.png",
    baseValue: 12,
    rarity: 3,
    categories: ["violet"],
    dice: ENEMY_DIE_FACES,
  },
  violet6: {
    id: "violet6",
    name: "violet6",
    space: [
      [1, 1],
      [1, 0],
      [1, 0],
      [1, 1],
    ],
    image: "items/violet6.png",
    baseValue: 1,
    rarity: 2,
    categories: ["violet"],
    dice: ENEMY_DIE_FACES,
  },
  white1: {
    id: "white1",
    name: "white1",
    space: [
      [0, 1],
      [0, 1],
      [1, 1],
    ],
    image: "items/white1.png",
    baseValue: 5,
    rarity: 5,
    categories: ["white"],
    dice: MULTIPLY_ATTACK_DIE_FACES,
  },
  white2: {
    id: "white2",
    name: "white2",
    space: [
      [1, 1],
      [1, 1],
      [1, 0],
      [1, 0],
    ],
    image: "items/white2.png",
    baseValue: 1,
    rarity: 2,
    categories: ["white"],
    dice: MULTIPLY_ATTACK_DIE_FACES,
  },
  white3: {
    id: "white3",
    name: "white3",
    space: [
      [1, 1],
      [1, 1],
      [1, 0],
    ],
    image: "items/white3.png",
    baseValue: 2,
    rarity: 2,
    categories: ["white"],
    dice: MULTIPLY_ATTACK_DIE_FACES,
  },
  white4: {
    id: "white4",
    name: "white4",
    space: [
      [1, 1, 0],
      [0, 1, 0],
      [0, 1, 0],
      [0, 1, 1],
    ],
    image: "items/white4.png",
    baseValue: 1,
    rarity: 2,
    categories: ["white"],
    dice: MULTIPLY_DEFENSE_DIE_FACES,
  },
  white5: {
    id: "white5",
    name: "white5",
    space: [[1]],
    image: "items/white5.png",
    baseValue: 16,
    rarity: 5,
    categories: ["white"],
    dice: MULTIPLY_DEFENSE_DIE_FACES,
  },
  white6: {
    id: "white6",
    name: "white6",
    space: [
      [0, 1, 1],
      [0, 1, 0],
      [1, 1, 0],
    ],
    image: "items/white6.png",
    baseValue: 2,
    rarity: 2,
    categories: ["white"],
    dice: MULTIPLY_DEFENSE_DIE_FACES,
  },
  yellow1: {
    id: "yellow1",
    name: "yellow1",
    space: [
      [1, 0],
      [1, 0],
      [1, 1],
      [1, 0],
    ],
    image: "items/yellow1.png",
    baseValue: 2,
    rarity: 2,
    categories: ["yellow"],
    dice: DAMAGE_DIE_FACES,
  },
  yellow2: {
    id: "yellow2",
    name: "yellow2",
    space: [
      [0, 1, 0],
      [1, 1, 1],
      [0, 1, 0],
    ],
    image: "items/yellow2.png",
    baseValue: 2,
    rarity: 4,
    categories: ["yellow"],
    dice: DAMAGE_DIE_FACES,
  },
  yellow3: {
    id: "yellow3",
    name: "yellow3",
    space: [[1], [1], [1]],
    image: "items/yellow3.png",
    baseValue: 8,
    rarity: 1,
    categories: ["yellow"],
    dice: DAMAGE_DIE_FACES,
  },
  yellow4: {
    id: "yellow4",
    name: "yellow4",
    space: [[1], [1], [1], [1]],
    image: "items/yellow4.png",
    baseValue: 5,
    rarity: 1,
    categories: ["yellow"],
    dice: EXTRA_SELECT_DIE_FACES,
  },
  yellow5: {
    id: "yellow5",
    name: "yellow5",
    space: [
      [1, 0],
      [1, 1],
      [0, 1],
      [0, 1],
    ],
    image: "items/yellow5.png",
    baseValue: 2,
    rarity: 2,
    categories: ["yellow"],
    dice: EXTRA_SELECT_DIE_FACES,
  },
  yellow6: {
    id: "yellow6",
    name: "yellow6",
    space: [
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 1],
    ],
    image: "items/yellow6.png",
    baseValue: 2,
    rarity: 2,
    categories: ["yellow"],
    dice: EXTRA_SELECT_DIE_FACES,
  },

  blue1: {
    id: "blue1",
    name: "blue1",
    space: [
      [1, 1],
      [1, 1],
      [0, 1],
    ],
    image: "items/blue1.png",
    baseValue: 2,
    rarity: 5,
    categories: ["yellow"],
    dice: ATTACK_DIE_FACES,
  },
  blue2: {
    id: "blue2",
    name: "blue2",
    space: [
      [0, 1],
      [1, 1],
    ],
    image: "items/blue2.png",
    baseValue: 8,
    rarity: 1,
    categories: ["yellow"],
    dice: DEFENSE_DIE_FACES,
  },
  blue3: {
    id: "blue3",
    name: "blue3",
    space: [
      [1, 1, 0],
      [0, 1, 0],
      [0, 1, 1],
    ],
    image: "items/blue3.png",
    baseValue: 2,
    rarity: 4,
    categories: ["yellow"],
    dice: HYBRID_DIE_FACES,
  },
  blue4: {
    id: "blue4",
    name: "blue4",
    space: [
      [0, 1],
      [1, 1],
      [1, 0],
      [1, 0],
    ],
    image: "items/blue4.png",
    baseValue: 2,
    rarity: 2,
    categories: ["yellow"],
    dice: ENEMY_DIE_FACES,
  },
  blue5: {
    id: "blue5",
    name: "blue5",
    space: [
      [0, 1],
      [0, 1],
      [0, 1],
      [1, 1],
    ],
    image: "items/blue5.png",
    baseValue: 2,
    rarity: 2,
    categories: ["yellow"],
    dice: MULTIPLY_ATTACK_DIE_FACES,
  },
  blue6: {
    id: "blue6",
    name: "blue6",
    space: [
      [0, 1],
      [1, 1],
      [1, 0],
    ],
    image: "items/blue6.png",
    baseValue: 5,
    rarity: 5,
    categories: ["yellow"],
    dice: MULTIPLY_DEFENSE_DIE_FACES,
  },
};

export default ItemBlueprints;
